
REPLACE INTO `biere` VALUES (1, 'Arraché', 'L''alliance de la lavande et de la violette offre l''accompagnement parfait pour tes moments festifs et te garantit une soirée mémorable.', 'Eau : 75%', 'Malt : 9% Pilsen ; 6.5% Pale Ale ; 0.5% Cara Gold', 'Houblon : 0.05% Strisselspalt ; 0.03% Citra ; 0.02% Irish Moss', 'Violette : 5.1%', 'Lavande : 3.4');
REPLACE INTO `biere` VALUES (2,'Aviné','La combinaison éxotique de mangue et de goyave crée le compagnon idéal pour ajouter une touche d''exotisme à tes soirées entre amis.','Eau : 75%','Malt : 9% Pilsen ; 6.5% Pale Ale ; 0.5% Cara Gold','Houblon : 0.05% Strisselspalt ; 0.03% Citra ; 0.02% Irish Moss','Goyave : 5.1%','Mangue : 3.4%');
REPLACE INTO `biere` VALUES (3,'Eméché','La pastèque associée à l''hibiscus délivre la boisson parfaite pour égayer tes moments de fête et ajouter une touche de fraîcheur à ta soirée.','Eau : 75%','Malt : 9% Pilsen ; 6.5% Pale Ale ; 0.5% Cara Gold','Houblon : 0.05% Strisselspalt ; 0.03% Citra ; 0.02% Irish Moss','Hibiscus : 5.1%','Pastèque : 3.4%');
REPLACE INTO `biere` VALUES (4,'Imbibé','La fusion de pomme et de poire de cette bière offre une expérience légère qui ajoute une touche de convivialité à tes moments entre amis.','Eau : 75%','Malt : 9% Pilsen ; 6.5% Pale Ale ; 0.5% Cara Gold','Houblon : 0.05% Strisselspalt ; 0.03% Citra ; 0.02% Irish Moss','Poire : 5.1%','Pomme : 3.4%');
REPLACE INTO `biere` VALUES (5,'Pompette','Avec sa saveur incroyable de framboise et de cerise, c''est la boisson qui va te faire danser sur la table et rendre ta soirée inoubliable.','Eau : 75%','Malt : 9% Pilsen ; 6.5% Pale Ale ; 0.5% Cara Gold','Houblon : 0.05% Strisselspalt ; 0.03% Citra ; 0.02% Irish Moss','Cerise : 5.1%','Framboise : 3.4%');
REPLACE INTO `biere` VALUES (6,'Torché','Laisse-toi séduire par ce mélange de myrtille et de grenade, c''est la bière qui fera de tes soirées des moments mémorables.','Eau : 75%','Malt : 9% Pilsen ; 6.5% Pale Ale ; 0.5% Cara Gold','Houblon : 0.05% Strisselspalt ; 0.03% Citra ; 0.02% Irish Moss','Myrtilles : 5.1%','Grenade : 3.4%');

REPLACE INTO `teammateMMI` VALUES (1,'Antoine','Chef d''équipe','');
REPLACE INTO `teammateMMI` VALUES (2,'Louis','Programmeur, animateur','Lorem ipsum');
REPLACE INTO `teammateMMI` VALUES (3,'Nathaël','Programmeur, infographiste','');
REPLACE INTO `teammateMMI` VALUES (4,'Noam','Infographiste','');
REPLACE INTO `teammateMMI` VALUES (5,'Tom','Monteur, community manager','Salut ! Moi c''est Tom, je suis étudiant en BUT Métiers du Multimédia et de l''Internet et j''ai fais partie du projet SAE de notre marque de bière ! Au cours de ce semestre, mon rôle a notamment été de réaliser les diapositives de nos rendus, faire le montage des vidéos et de communiquer sur les réseaux  sociaux !');

REPLACE INTO `teammateGB` VALUES (1,'Antonin','Fabricant','Bonjour, je suis Antonin Gauchy un étudiant en Génie Biologique, je suis quelqu''un de joyeux et sympathique et au cours de cette SAE j''ai participé en temps que membre de groupe à la préparation de la bière !');
REPLACE INTO `teammateGB` VALUES (2,'Lana','Cheffe d''équipe','Salut, je suis Lana. Passionnée par la nature et les animaux, j''ai été la cheffe de groupe de mon équipe de génie biologique  durant ce projet de fabrication d''une bière. Ce fut une expérience très enrichissante !');
REPLACE INTO `teammateGB` VALUES (3,'Léonie','Farbricant','');